# Generated by Django 5.0 on 2023-12-16 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kuzov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipkuzova', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naim', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModelAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimenovanie', models.CharField(max_length=50)),
                ('izobrazhenie', models.CharField(blank=True, max_length=200, null=True)),
                ('photoosobennosti', models.CharField(blank=True, max_length=200, null=True)),
                ('photo1', models.CharField(blank=True, max_length=200, null=True)),
                ('photo2', models.CharField(blank=True, max_length=200, null=True)),
                ('photo3', models.CharField(blank=True, max_length=200, null=True)),
                ('clirens', models.FloatField(blank=True, default=0.0, null=True)),
                ('kolesa', models.CharField(blank=True, max_length=50, null=True)),
                ('toplivo', models.CharField(blank=True, max_length=50, null=True)),
                ('korobkaperedach', models.CharField(blank=True, max_length=50, null=True)),
                ('privod', models.CharField(blank=True, max_length=50, null=True)),
                ('osobennosti', models.TextField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('opisanie', models.TextField(blank=True, null=True)),
                ('shirina', models.FloatField(blank=True, default=0.0, null=True)),
                ('visota', models.FloatField(blank=True, default=0.0, null=True)),
                ('dlina', models.FloatField(blank=True, default=0.0, null=True)),
                ('stepensjatiya', models.FloatField(blank=True, default=0.0, null=True)),
                ('mochnost', models.FloatField(blank=True, default=0.0, null=True)),
                ('obembaka', models.FloatField(blank=True, default=0.0, null=True)),
                ('kuzov', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoapp.kuzov')),
                ('marka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoapp.marka')),
            ],
        ),
    ]
