name: Deploy to Docker

on:
  push:
    branches:
      - main  # замените на вашу основную ветку, например, master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: 109.195.38.77
      DATABASE_PORT: 5432
      SECRET_KEY: test-secret-key
      DEBUG: 'True'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/myproject:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/myproject:latest

    - name: SSH to server and deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 24
        script: |
           docker run -d --rm -e DATABASE_HOST=109.195.38.77 -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/myproject:latest
